# Generated by Django 3.0.6 on 2020-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('fields_of_work', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=25)),
                ('skills_required', models.CharField(max_length=500)),
                ('no_of_internships', models.IntegerField()),
                ('perks', models.CharField(max_length=100)),
                ('who_can_apply', models.CharField(max_length=200)),
            ],
        ),
    ]
