# Generated by Django 3.0.6 on 2020-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentureCapitalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=5000)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
