# Generated by Django 3.0.7 on 2020-06-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.CharField(max_length=25),
        ),
    ]
