# Generated by Django 3.0.8 on 2020-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0002_auto_20200813_1333'),
        ('internshipPortal', '0002_auto_20200802_1125'),
    ]

    operations = [
    ]
