# Generated by Django 3.0.7 on 2020-08-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0002_auto_20200809_1355'),
        ('internshipPortal', '0002_auto_20200802_1125'),
    ]

    operations = [
    ]
