# Generated by Django 3.0.6 on 2020-07-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
        ('internshipPortal', '0002_venturecapitalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.StartupProfile'),
        ),
    ]
