# Generated by Django 3.0.6 on 2020-07-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
        ('internshipPortal', '0003_auto_20200710_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='fields_of_work',
        ),
        migrations.AddField(
            model_name='internship',
            name='applied_by',
            field=models.ManyToManyField(default='', related_name='internships_applied', to='user.StudentProfile'),
        ),
        migrations.AddField(
            model_name='internship',
            name='field_of_internship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='startup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='internships_created', to='user.StartupProfile'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='no_of_internships',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.IntegerField(),
        ),
    ]
