# Generated by Django 3.0.6 on 2020-07-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
        ('internshipPortal', '0004_auto_20200710_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='who_can_apply',
            new_name='who_should_apply',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='applied_by',
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=1200)),
                ('resume', models.URLField(default='')),
                ('applied_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.StudentProfile')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internshipPortal.Internship')),
            ],
        ),
    ]
