# Generated by Django 3.0.6 on 2020-07-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
        ('internshipPortal', '0007_auto_20200710_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='applied_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='user.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='internshipPortal.Internship'),
        ),
    ]
