# Generated by Django 3.0.6 on 2020-07-11 18:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0008_auto_20200710_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venturecapitalist',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='venturecapitalist',
            name='industries',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='venturecapitalist',
            name='photo',
            field=models.ImageField(default='', upload_to='vc/'),
        ),
        migrations.AddField(
            model_name='venturecapitalist',
            name='startups_funded',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='venturecapitalist',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='venturecapitalist',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
