# Generated by Django 3.0.7 on 2020-07-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0010_auto_20200713_1455'),
        ('internshipPortal', '0010_auto_20200713_0944'),
    ]

    operations = [
    ]
