# Generated by Django 3.0.6 on 2020-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0010_auto_20200713_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='apply_by',
            field=models.DateField(default='2000-01-01', help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.CharField(max_length=100),
        ),
    ]
