# Generated by Django 3.0.7 on 2020-07-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0011_auto_20200713_2225'),
        ('internshipPortal', '0011_merge_20200713_1916'),
    ]

    operations = [
    ]
