# Generated by Django 3.0.6 on 2020-07-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0012_merge_20200713_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='apply_by',
            field=models.DateField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.'),
        ),
    ]
