# Generated by Django 3.0.6 on 2020-07-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0013_auto_20200714_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.URLField(default='', help_text='Add the drive link to your resume.'),
        ),
    ]
