# Generated by Django 3.0.6 on 2020-07-06 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='', max_length=50)),
                ('about_the_author', models.CharField(max_length=150)),
                ('author_image', models.ImageField(default='default.jpg', upload_to='author_images')),
                ('blog_image', models.ImageField(default='default.jpg', upload_to='blog_images')),
            ],
        ),
    ]
