# Generated by Django 3.0.6 on 2020-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_the_author',
            field=models.TextField(max_length=1000),
        ),
    ]
