# Generated by Django 3.0.6 on 2020-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200706_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_the_author',
            field=models.TextField(max_length=700),
        ),
    ]
