# Generated by Django 3.0.6 on 2020-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, default='user.png', upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='blog_images'),
        ),
    ]
