# Generated by Django 3.0.7 on 2020-07-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investors',
            new_name='Investor',
        ),
    ]
