# Generated by Django 3.0.7 on 2020-07-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_auto_20200713_0944'),
        ('investors', '0004_auto_20200713_1455'),
    ]

    operations = [
    ]
