# Generated by Django 3.0.6 on 2020-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
