# Generated by Django 3.0.6 on 2020-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='startupprofile',
            old_name='fieldofwork',
            new_name='field_of_work',
        ),
        migrations.RenameField(
            model_name='startupprofile',
            old_name='startupname',
            new_name='startup_name',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='founder',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='startup/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
