# Generated by Django 3.0.8 on 2020-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200808_2228'),
        ('user', '0002_auto_20200813_1333'),
    ]

    operations = [
    ]
