# Generated by Django 3.0.6 on 2020-07-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
    ]
