# Generated by Django 3.0.6 on 2020-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200707_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='user',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
