# Generated by Django 3.0.6 on 2020-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200702_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
