# Generated by Django 3.0.7 on 2020-07-02 15:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200702_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
