# Generated by Django 3.0.6 on 2020-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200711_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='city',
            new_name='city_of_residence',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='area_of_specialization',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(default='', max_length=50),
        ),
    ]
