# Generated by Django 3.0.6 on 2020-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200711_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupprofile',
            old_name='about',
            new_name='about_the_startup',
        ),
        migrations.RenameField(
            model_name='startupprofile',
            old_name='founder',
            new_name='founders',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='startup_logo',
            field=models.ImageField(blank=True, default='download.png', upload_to='startup/'),
        ),
    ]
