# Generated by Django 3.0.7 on 2020-07-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200712_0013'),
        ('user', '0007_auto_20200711_2357'),
    ]

    operations = [
    ]
