# Generated by Django 3.0.7 on 2020-07-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200712_0039'),
        ('user', '0008_merge_20200712_0401'),
    ]

    operations = [
    ]
